name: Update Streak Stats

on:
  schedule:
    - cron: "0 4 * * *" # Runs at 4 AM UTC every day
  workflow_dispatch: # Allows you to run it manually

jobs:
  update-streak:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Try to download the image. 
      # We increase timeout to 60s to give the server more time to calculate your 9k+ commits
      - name: Download Streak Image
        run: |
          curl --max-time 60 -o streak-stats.svg "https://streak-stats.demolab.com?user=kishorewv1207&theme=transparent&hide_border=true"

      # Check if the file was downloaded and push it
      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add streak-stats.svg
          # Only commit if the file has changed
          git commit -m "Update streak stats" || exit 0
          git push
